# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17cf65cb15428cfc4a2c656503c725f442cdbee28860e9611f932ef295169b047690da5aa1be43ccb2b58a463363e67d0b189314da15ae67bcbc0859e17c7b75

test:
  secret_key_base: 2aa8cc4910a03e9cfec5f6db9fc8e2f276b3f56bde0cc32175c7e03f3513740b24a8ecbcd3ed920a04437bacb10cbdb7a595436e6af4258a24d6854ceaafbab7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
